version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: web_13
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Roksi2015
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data